# Generated by Django 3.2.5 on 2022-07-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='what a great Post!'),
            preserve_default=False,
        ),
    ]
